---
- hosts: localhost
  tasks:

  - name: load env specific vars
    include_vars:
      dir: group_vars
      files_matching: "{{ env }}.yml"
    tags:
      - vars

  - name: create bucket to store templates
    shell: |
      aws s3 mb s3://{{ s3_bucket }} --profile {{ aws_profile }}
    ignore_errors: yes
    tags:
      - bucket

  - name: validate template locally
    shell: |
      aws cloudformation validate-template --template-body file://ocis-cf-template.json
    tags:
      - validate

  - name: create a stack, pass in the template via an URL
    cloudformation:
      stack_name: "ocis-test-stack-test"
      state: present
      region: ap-southeast-2
      disable_rollback: fasle
      template: https://ocis-cf-template.json
      template_parameters:
        VpcId: vpc-78e76e1f
        PrivSubnets: "subnet-5b047812,subnet-c4d192a"
        PrivSubnet: subnet-5b047812
        ClusterSize: 3
      tags:
        Application: OCISTEST
        Owner: ContinoGreenTeam
        Contact: andrew.khoury@origin.com.au
        Project: CloudMigration
        Environment: NonProd
    tags:
      - cf

  - name: create CF
    shell: |
      aws cloudformation create-stack \
      --stack-name ocis-test-stack \
      --template-body file://ocis-cf-template.json \
      --parameters ParameterKey=VpcId,ParameterValue=vpc-78e76e1f ParameterKey=PrivSubnets,ParameterValue=subnet-5b047812\\,subnet-c4d192a ParameterKey=PrivSubnet,ParameterValue=subnet-5b047812 \
      --tags Key=Application,Value=OCISTEST Key=Owner,Value=ContinoGreenTeam Key=Contact,Value=andrew.khoury@origin.com.au Key=Project,Value=CloudMigration Key=Environment,Value=NonProd \
      --profile {{ aws_profile }}
    tags:
      - cf
      
  - name: Upload template to s3
    shell: |
      aws s3 cp ocis-cf-template.json s3://{{ s3_bucket }}/ocis-cf-template.json --profile {{ aws_profile }}
    tags:
      - ams

  - name: Generate pre-signed file
    shell: |
      aws s3 presign --expires-in 86400 s3://{{ s3_bucket }}/ocis-cf-template.json
    register: cf_templated_presign    
    tags:
      - ams

  - name: generate ocis params file
    template:
      src: ocisp-arameters-template.json
      dest: ocis-params-GENERATED.json
    tags:
      - ams
      
  - name: create RFC
    shell: |
      aws amscm create-rfc \
      --change-type-id ct-36cn2avfrrj9v --change-type-version "1.0" \
      --title "TEST ONLY - IGNORE - Contino test cfn ingest v2" \
      --execution-parameters "file://ocis-params-GENERATED.json" --region us-east-1
    register: rcf_id
    tags:
      - ams
      - ams_create

  - name: submit RFC
    shell: |
      aws amscm submit-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --region us-east-1
    tags:
      - ams
      - ams_create

  - name: check RFC
    shell: |
      aws amscm get-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --query "Rfc.{Status:Status.Name,Exec:ExecutionOutput}" --region us-east-1
    retries: 60
    delay: 30
    register: result
    until: (result.stdout | from_json).Status == "Success"
    tags:
      - ams
      - ams_create
