---
- hosts: localhost
  tasks:

  - name: load env specific vars
    include_vars:
      dir: group_vars
      files_matching: "{{ env }}.yml"
    tags:
      - vars

  # STACK ID START
  - name: Get list of stacks
    shell: |
      aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query "StackSummaries[*].{StackName:StackName, TemplateDescription:TemplateDescription}" --output table
    register: cf_stacks

  - name: Show list of stacks
    debug:
      msg: "{{ cf_stacks.stdout_lines }}"

  - name: What stack do you want access to?
    pause:
      prompt: "Stack Id?"
    register: stack_id 
  # STACK ID END

  - name: create bucket to store templates
    shell: |
      aws s3 mb s3://{{ s3_bucket }} --profile {{ aws_profile }}
    ignore_errors: yes
    tags:
      - bucket

  - name: validate template locally
    shell: |
      aws cloudformation validate-template --template-body file://templates/ocis-cf.json
    tags:
      - validate

  - name: create a stack, pass in the template via an URL
    cloudformation:
      stack_name: "ocis-test-stack-test"
      state: present
      region: ap-southeast-2
      disable_rollback: fasle
      template: https://templates/ocis-cf.json
      template_parameters:
        VpcId: vpc-78e76e1f
        PrivSubnets: "subnet-5b047812,subnet-c4d192a"
        PrivSubnet: subnet-5b047812
        ClusterSize: 3
      tags:
        Application: OCISTEST
        Owner: ContinoGreenTeam
        Contact: andrew.khoury@origin.com.au
        Project: CloudMigration
        Environment: NonProd
    tags:
      - cf

  - name: create CF
    shell: |
      aws cloudformation create-stack \
      --stack-name ocis-test-stack \
      --template-body file://templates/ocis-cf.json \
      --parameters ParameterKey=VpcId,ParameterValue=vpc-78e76e1f ParameterKey=PrivSubnets,ParameterValue=subnet-5b047812\\,subnet-c4d192a ParameterKey=PrivSubnet,ParameterValue=subnet-5b047812 \
      --tags Key=Application,Value=OCISTEST Key=Owner,Value=ContinoGreenTeam Key=Contact,Value=andrew.khoury@origin.com.au Key=Project,Value=CloudMigration Key=Environment,Value=NonProd \
      --profile {{ aws_profile }}
    tags:
      - cf
      
  - name: Upload ocis-cf.json template to s3
    shell: |
      aws s3 cp templates/ocis-cf.json s3://{{ s3_bucket }}/ocis-cf.json --profile {{ aws_profile }}
    tags:
      - ams

  - name: Generate pre-signed url for ocis-cf.json
    shell: |
      aws s3 presign --expires-in 3600 s3://{{ s3_bucket }}/ocis-cf.json --profile {{ aws_profile }}
    register: cf_templated_presign    
    tags:
      - ams

  - name: generate exec-params_cfn-create.json
    template:
      src: templates/exec-params_cfn-create.json
      dest: outputs/exec-params_cfn-create.json
    tags:
      - ams

  - name: Upload exec-params_cfn-create.json to s3
    shell: |
      aws s3 cp outputs/exec-params_cfn-create.json s3://{{ s3_bucket }}/exec-params_cfn-create.json --profile {{ aws_profile }}
    tags:
      - ams

  - name: Generate pre-signed file for exec-params_cfn-create.json
    shell: |
      aws s3 presign --expires-in 3600 s3://{{ s3_bucket }}/exec-params_cfn-create.json --profile {{ aws_profile }}
    register: cf_templated_presign_params_generated    
    tags:
      - ams

  - name: generate exec-params_cfn-update.json
    template:
      src: templates/exec-params_cfn-update.json
      dest: outputs/exec-params_cfn-update.json
    tags:
      - ams
      
  - name: update RFC
    shell: |
      aws amscm create-rfc \
      --change-type-id ct-0xdawir96cy7k --change-type-version "1.0" \
      --title "TEST - Contino test cfn MANUAL UPDATE REQUEST - {{ env }}" \
      --execution-parameters "file://outputs/exec-params_cfn-update.json" --region us-east-1
    register: rcf_id
    tags:
      - ams
      - ams_create

  - name: submit RFC
    shell: |
      aws amscm submit-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --region us-east-1
    tags:
      - ams
      - ams_create

  - name: check RFC
    shell: |
      aws amscm get-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --query "Rfc.{Status:Status.Name,Exec:ExecutionOutput}" --region us-east-1
    retries: 60
    delay: 30
    register: result
    until: (result.stdout | from_json).Status == "Success"
    tags:
      - ams
      - ams_create
