---
- hosts: localhost
  tasks:

  - name: load env specific vars
    include_vars:
      dir: group_vars
      files_matching: "{{ env }}.yml"
    tags:
      - vars

  - name: Get list of stacks
    shell: |
      aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query "StackSummaries[*].{StackName:StackName, TemplateDescription:TemplateDescription}" --output table
    register: cf_stacks

  - name: Show list of stacks
    debug:
      msg: "{{ cf_stacks.stdout_lines }}"

  - name: What stack do you want access to?
    pause:
      prompt: "Stack Id?"
    register: stack_id 

  - name: generate ocis params file
    template:
      src: bastion-access-params.json
      dest: bastion-access-params-GENERATED.json

  - name: create RFC
    shell: |
      aws amscm create-rfc \
      --change-type-id ct-1dmlg9g1l91h6 --change-type-version "1.0" \
      --title "Request for Access" \
      --execution-parameters "file://bastion-access-params-GENERATED.json" --region us-east-1
    register: rcf_id

  - name: submit RFC
    shell: |
      aws amscm submit-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --region us-east-1

  - name: check RFC
    shell: |
      aws amscm get-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --query "Rfc.{Status:Status.Name,Exec:ExecutionOutput}" --region us-east-1
    retries: 120
    delay: 5
    register: result
    until: (result.stdout | from_json).Status == "Success"

  - name: Get RFC Output
    shell: |
      aws amscm get-rfc --rfc-id {{ (rcf_id.stdout | from_json).RfcId }} --query "Rfc.{Exec:ExecutionOutput}" --region us-east-1
    register: view_rfc

  - name: Show RFC Output
    debug:
      msg: "{{ (view_rfc.stdout | from_json).Exec }}"
