aws_profile: origin-anp
s3_bucket:   contino-green-team

Description: OCIS Application Stack - Contains 1 x Web/App server, 1 x Reporting Server, and a RDS database.
Name:        OCIS Parameters

Application: OCIS
Owner:       Colin Beames
Contact:     Colin.Beames@origin.com.au
Project:     OCIS

username: lastf
stack_id: stack-xxx